### ISSUE TITLE
How to use with Postgres' ArrayField?

### ISSUE THREAD

**Issue by alfonsrv** [testdrivenio/django-search#1]
Great writeup on TestDriven.io! I was wondering if there was a way to use Postgres' SearchVectors with Postgres' ArrayFields.

I fiddled around a bit but couldn't get it to work. Any ideas?

**Comment by mjhea0** [comment]
Not really sure. Did you see https://stackoverflow.com/questions/47242639/how-to-add-an-arrayfield-to-a-searchvector-in-django?
